### ISSUE TITLE
Crashes my Blender session

### ISSUE THREAD

**Issue by DrBobSmith** [macio97/Real-Snow#1]
On a complicated scene, blender becomes busy and never returns.  When I tried the default cube, the patch of snow was under the cube.  So I added a plane.  That added the snow on top. No other surface I could find.

In the real world, snow goes from the sky down.  I got snow to appear underneath a cylinder.  I couldn't get the snow on top except by doing a 180 degree on the X axis.

I added a monkey.  Again, the snow was under the monkey and not on top.

**Comment by DrBobSmith** [comment]
Windows 10 Professional.
Blender 2.90.1.
Dell XPS-8500
eVga Geforce GTX 1660 card.
24 GB of RAM.

I am following a different tutorial for RealSnow, figuring that I am making the mistake.  https://www.youtube.com/watch?v=kMRhtmMMwE0 and I am about 5 minutes in.  He is selecting faces in Layout -> Edit mode and then using RealSnow.  Should be simple, but while RealSnow appears on the right in Object mode under Layout, it disappears under Edit mode.  So I can't apply it to part of the item.

I was going to put snow on a simple UV sphere.  I could grab faces in Layout -> Edit -> Select (box select) super easy, no problem.  But no RealSnow!!!!

**Comment by marcopavanello** [comment]
The add-on works only in Object Mode, in fact if you see in the tutorial he is selecting the faces and then he goes back to Object Mode.
Strange that you are getting this behaviour, i'm curious to know if you are getting any errors, maybe could you open the console? To do that just go in Window > Console to view it.
Anyway, i just tested in 2.90.1 and it works for me, maybe you have the normals of your objects inverted?
