### ISSUE TITLE
Another BL_Category

### ISSUE THREAD

**Issue by Ulf3000** [macio97/Real-Snow#2]
Hi are you the dev of this addon ? 

my suggestionb is to change : 

bl_label = "Real Snow"
bl_category = "Create"

there are too many npanel ..

another option would be to add a preference to choose , like grease pencil tools and some others have .

**Comment by marcopavanello** [comment]
Hey, why would you do that? Would that make the add-on disappear from the N panel? If so then where would the UI go?

**Comment by Ulf3000** [comment]
it would just put the ui into the "create" npanel .. why? becasue there are too many npanels and its confusing

**Comment by marcopavanello** [comment]
If it's not an official Blender UI design choice then I think I will keep it as is.
