### ISSUE TITLE
Elaboration progress and multithread

### ISSUE THREAD

**Issue by joaulo** [macio97/Real-Snow#3]
Hi, I don't know if this is the place to submit a _feature request_, but I just used this add-on and it's really good. Unfortunately I noticed that there is no **progress indicator** in snow processing and for long-term processing I think it can be useful to understand if it is progressing and how long it could take. I tried to use it on some trees made with the sapling addon and it took a really long time but having no visual output I had several times the doubt that it was not working.
Still on the subject of processing times, I noticed that the process uses **only one CPU core** at 100%, would it be possible to use all cores?
Thanks for this addon and for your work

**Comment by marcopavanello** [comment]
I don't think it's possible since we are using the Blender version of Python, and unfortunately the progress bar is not exposed to the Python API.
