### ISSUE TITLE
Blender just freezes

### ISSUE THREAD

**Issue by tarnum888** [macio97/Real-Snow#5]
After pressing the Add Snow button, the blender freezes and nothing happens, even after a long wait time.

**Comment by tarnum888** [comment]
Blender version 2.93

**Comment by marcopavanello** [comment]
Well since the time depends on how complex the model you are applying the snow to, then may I ask you to send me the blend file with the model?

**Comment by tarnum888** [comment]
Any model freezes blender, even if i want to place snow on a base simple plane
On blender version 2.83, there is no such problem, but on 2.93.1 some kind of trouble

**Comment by tarnum888** [comment]
However, it doesn't matter, you can close the tab, it looks like there is a problem with the steam version of the blender, on another computer everything works perfectly

**Comment by tarnum888** [comment]
I figured out what was causing the problem, my unit scale is set to 0.01 instead of 1. This change affects the work of the addon
![Screenshot 2021-07-26 143019](https://user-images.githubusercontent.com/16664930/126925156-210accc6-9362-4b5b-9d6b-8beb647c7f50.png)

**Comment by marcopavanello** [comment]
Glad you solved the issue but, can't reproduce the different behavior you were getting either, changing unit changes nothing on my end...
