### ISSUE TITLE
Snow not rendering correctly

### ISSUE THREAD

**Issue by LetsRive-dev** [macio97/Real-Snow#6]
Hey I downloaded the addon a couple of days ago but it doesnt seem to work properly. Instead of fluffy snow it is just a shiny and edgy surface
![plwHhOTc](https://user-images.githubusercontent.com/77113739/158694048-792d6f8c-d482-4df1-bc61-54a896d123af.png)
.

**Comment by marcopavanello** [comment]
Hey, you don't have to download the add-on as it's already included in Blender. It seems you are using Eevee, the snow material makes use of displacement so switch to Cycles and switch to Experimental mode?

**Comment by LetsRive-dev** [comment]
I think the problem was that everything was exremely small and so when I scaled it up it worked. Sorry for causing an inconvienience and thank you so much for creating this wonderful tool!
